spark:
  image: colla/hadoop_spark
  container_name: spark
  links:
   - mongo

api:
   image: colla/api_mongodb
   container_name: api
   links:
    - mongo
   ports: 
    - 5000:5000

mongo:
   image: colla/mongodb
   container_name: mongo
   ports:
    - 27017:27017

